baseurl:
title: Reliability Quest
author: Reliability Quest
description: Making asset performance management simple.
name: Reliability Quest
markdown: kramdown
permalink: /articles/:short_year/:title
timezone: America/New_York
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md', 'node_modules']
destination: ./docs
